### ISSUE TITLE
Gradlev is unable to determine openjdk 11 on ubuntu 18.04

### ISSUE THREAD

**Issue by planthaber** [sebastianstock/chimp#1]
Hi, 

`./gradlew fatjar` with a sandard install in ubuntu 18.04 gives following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

10.0.2 is the version returned by javac --version.

When setting JAVA_HOME to openjdk jdk 8

`export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/`

It compiles fine.

**Comment by sebastianstock** [comment]
This should have been fixed by the gradlew update a couple of months ago.
It works for me on Ubuntu 18.04 with openjdk 11.
