### ISSUE TITLE
Dead link to paper

### ISSUE THREAD

**Issue by XB32Z** [sebastianstock/chimp#3]
The link to the paper in the README.md is dead. Also it would be nice to have an explanation or how to

**Comment by oscar-lima** [comment]
can be found here: http://130.243.105.49/~mmi/papers/iros15-chimp.pdf

**Comment by oscar-lima** [comment]
actually the link from the README works for me...

**Comment by XB32Z** [comment]
Hello, ah yes it works now ... strange it didn't work earlier. Sorry
